% Provided data for Monet paintings
% Monet: TN = 45, FP = 5, FN = 1, TP = 49

% Construct the confusion matrix based on the provided data
conf_matrix = [49, 1; 5, 45];

% Display the confusion matrix
disp('Confusion Matrix for Monet Paintings: ');
disp(conf_matrix);

% Visualize the confusion matrix using a heatmap
figure;
h = heatmap(conf_matrix, 'Title', 'Confusion Matrix for Monet Paintings', 'XLabel', 'Predicted', 'YLabel', 'Actual');

% Display the numbers in the cells
h.CellLabelFormat = '%d';

% Add a guide to the side of the heatmap
annotation('textbox', [0.93, 0.825, 0.1, 0.1], 'String', ...
    {'Statistics:', ...
     'Precision: 0.91', ...
     'Recall: 0.98', ...
     'F1 Score: 0.94', ...
     'Accuracy: 0.94', ...
     'TN: 45', ...
     'FP: 5', ...
     'FN: 1', ...
     'TP: 49'}, ...
    'FitBoxToText', 'on', 'BackgroundColor', 'white');